$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: pc_segment-aml-environment
image: mcr.microsoft.com/azureml/curated/acpt-pytorch-1.13-cuda11.7:latest
conda_file: conda.yml
description: Environment created from a Docker image plus Conda environment.